/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/communities/{ref}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the community's whole configuration: categories, workflow labels, roles and rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ref: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityConfig"];
                    };
                };
            };
        };
        /** Import a configuration: the UI picks up new categories and status names immediately */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ref: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityConfig"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityConfig"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept: the case moves to In progress and residents see who is helping */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline with an optional note {"note": "..."}; the moderator sees why */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoteBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redirect: someone else should do this; the note says who */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoteBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentView"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case status: timeline, who is helping, the checklist and the playbook used */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaseDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{id}/help-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** "I can help": the caller becomes a volunteer near the case; moderators see the offer and can add them when they approve the match. Optional {"note": "..."} */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HelpOfferBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HelpOffer"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** "Did this help?" HELPED confirms a resolved case (it closes and the AI drafts the next playbook version); NOT_HELPED reopens it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomeBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaseDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{id}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** "Me too": backs the case without writing a report; the caller follows it from now on */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaseDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Doer update for residents: text and photos; resolve=true marks the case resolved */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBody"];
                    "multipart/form-data": {
                        text?: string;
                        resolve?: boolean;
                        photo?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaseDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Communities on this deployment (city districts, campuses, housing co-ops) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration for the UI: categories, status labels and languages, in the reader's language */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doer/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** New and active assignments (status=OFFERED,ACCEPTED by default; status=all for every one) */
        get: {
            parameters: {
                query?: {
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home map: public cases with locations rounded to the community's grid, plus initiatives in view */
        get: {
            parameters: {
                query?: {
                    bbox?: string;
                    community?: string;
                    layers?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their roles in each community (demo login: X-Demo-User header) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases the caller reported, backs or follows, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyCase"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A photo or voice note. Report media: author, moderators and assigned doers; update photos: whoever can see the case. In <img> tags pass the demo login as ?as= */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full case for the moderator: every report, the timeline and the AI's pending suggestion */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModerationDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases waiting for a decision, by urgency then support; filter by kind (NEED, IDEA) and urgency */
        get: {
            parameters: {
                query?: {
                    community?: string;
                    kind?: string;
                    urgency?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/suggestions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve the match: optional playbookVersionId and actorIds override the AI's picks. Creates the assignments and the checklist, and notifies the doers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModerationDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ideas library: playbooks a community can use (its own and shared ones). q searches by meaning, e.g. ?q=lonely seniors without a lift */
        get: {
            parameters: {
                query?: {
                    community?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybookItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks/{id}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard a draft; a playbook that only had this draft is removed with it */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    number: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks/{id}/versions/{number}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make the draft the current version; the previous one is archived */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    number: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybookView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A playbook by id or slug: current version, the waiting draft, results and version history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ref: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybookView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New report: text (typed or transcribed), optional voice note and photos, location. Returns 202; REPORT_PROCESSED arrives on /api/stream when the AI has read it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewReportBody"];
                    "multipart/form-data": {
                        community?: string;
                        kind?: components["schemas"]["ReportKind"];
                        text?: string;
                        /** Format: double */
                        lat?: number;
                        /** Format: double */
                        lng?: number;
                        address?: string;
                        anonymous?: boolean;
                        /** Format: binary */
                        audio?: string;
                        photo?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review step: what the AI understood, and the closest open case nearby (join it or open a new one) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the review: {"caseId": ...} joins that case, no caseId opens a new one. Edited title, summary, category or urgency replace the AI's */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitReport"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmitResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events for everything the caller may see. EventSource cannot send headers, so pass the demo login as ?as=maria */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["StreamEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tick (or untick) a checklist step: {"done": true} */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskView"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActorRef: {
            id?: components["schemas"]["UUID"];
            name?: string;
            kind?: string;
        };
        AiReading: {
            language?: string;
            categoryCode?: string;
            categoryLabel?: string;
            urgency?: string;
            safetyConcern?: boolean;
            title?: components["schemas"]["TextDto"];
            summary?: components["schemas"]["TextDto"];
            engine?: string;
        };
        Alternative: {
            playbookId?: components["schemas"]["UUID"];
            versionId?: components["schemas"]["UUID"];
            title?: components["schemas"]["TextDto"];
            origin?: string;
            /** Format: double */
            similarity?: number;
        };
        Approval: {
            playbookVersionId?: components["schemas"]["UUID"];
            actorIds?: string[];
        };
        AssignmentView: {
            id?: components["schemas"]["UUID"];
            status?: string;
            createdAt?: components["schemas"]["Instant"];
            respondedAt?: components["schemas"]["Instant"];
            note?: components["schemas"]["TextDto"];
            actor?: components["schemas"]["ActorRef"];
            case?: components["schemas"]["CaseCard"];
            summary?: components["schemas"]["TextDto"];
            playbook?: components["schemas"]["PlaybookRef"];
            tasks?: components["schemas"]["TaskView"][];
            /** Format: int32 */
            tasksDone?: number;
            team?: components["schemas"]["Helper"][];
            assignedBy?: string;
        };
        CandidateView: {
            actorId?: components["schemas"]["UUID"];
            name?: string;
            kind?: string;
            reason?: components["schemas"]["TextDto"];
            /** Format: double */
            score?: number;
            selected?: boolean;
        };
        CaseCard: {
            id?: components["schemas"]["UUID"];
            number?: string;
            kind?: string;
            title?: components["schemas"]["TextDto"];
            categoryCode?: string;
            categoryLabel?: string;
            status?: string;
            statusLabel?: string;
            urgency?: string;
            areaLabel?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            exactLocation?: boolean;
            /** Format: int32 */
            reportCount?: number;
            /** Format: int32 */
            supporterCount?: number;
            createdAt?: components["schemas"]["Instant"];
            updatedAt?: components["schemas"]["Instant"];
            community?: components["schemas"]["CommunityRef"];
        };
        CaseDetail: {
            /** Format: double */
            lng?: number;
            exactLocation?: boolean;
            kind?: string;
            categoryLabel?: string;
            categoryCode?: string;
            areaLabel?: string;
            title?: components["schemas"]["TextDto"];
            community?: components["schemas"]["CommunityRef"];
            statusLabel?: string;
            number?: string;
            createdAt?: components["schemas"]["Instant"];
            urgency?: string;
            /** Format: int32 */
            supporterCount?: number;
            /** Format: int32 */
            reportCount?: number;
            id?: components["schemas"]["UUID"];
            /** Format: double */
            lat?: number;
            status?: string;
            updatedAt?: components["schemas"]["Instant"];
            summary?: components["schemas"]["TextDto"];
            resolvedAt?: components["schemas"]["Instant"];
            closedAt?: components["schemas"]["Instant"];
            playbook?: components["schemas"]["PlaybookRef"];
            helpers?: components["schemas"]["Helper"][];
            tasks?: components["schemas"]["TaskView"][];
            outcomes?: components["schemas"]["Outcomes"];
            timeline?: components["schemas"]["TimelineItem"][];
            me?: components["schemas"]["CaseMe"];
        };
        CaseMe: {
            signedIn?: boolean;
            moderator?: boolean;
            participant?: boolean;
            participantRole?: string;
            outcome?: string;
            canAnswerOutcome?: boolean;
            assignmentId?: components["schemas"]["UUID"];
            assignmentStatus?: string;
            canPostUpdate?: boolean;
        };
        /** @enum {string} */
        CaseStatus: "NEW" | "TRIAGED" | "SUGGESTED" | "MATCHED" | "IN_PROGRESS" | "RESOLVED" | "CONFIRMED" | "CLOSED" | "REJECTED";
        Category: {
            code?: string;
            labels?: {
                [key: string]: string;
            };
        };
        CategoryView: {
            code?: string;
            label?: string;
        };
        CommunityConfig: {
            categories?: components["schemas"]["Category"][];
            workflow?: components["schemas"]["WorkflowState"][];
            roles?: components["schemas"]["RoleInfo"][];
            rules?: components["schemas"]["Rules"];
        };
        CommunityItem: {
            slug?: string;
            kind?: string;
            name?: string;
        };
        CommunityRef: {
            slug?: string;
            name?: string;
        };
        CommunityView: {
            id?: components["schemas"]["UUID"];
            slug?: string;
            kind?: string;
            name?: string;
            lang?: string;
            defaultLocale?: string;
            locales?: string[];
            categories?: components["schemas"]["CategoryView"][];
            statuses?: components["schemas"]["StatusView"][];
            roles?: components["schemas"]["RoleView"][];
            rules?: components["schemas"]["RulesView"];
            me?: components["schemas"]["MyPlace"];
        };
        EffortView: {
            coordinatorTime?: string;
            budget?: string;
            firstHelp?: string;
        };
        HelpOffer: {
            caseId?: components["schemas"]["UUID"];
            actorId?: components["schemas"]["UUID"];
            actorName?: string;
        };
        HelpOfferBody: {
            note?: string;
        };
        Helper: {
            assignmentId?: components["schemas"]["UUID"];
            actorId?: components["schemas"]["UUID"];
            name?: string;
            kind?: string;
            status?: string;
        };
        /**
         * Format: date-time
         * @example 2022-03-10T16:15:50Z
         */
        Instant: string;
        MapInitiative: {
            id?: components["schemas"]["UUID"];
            title?: components["schemas"]["TextDto"];
            description?: components["schemas"]["TextDto"];
            schedule?: components["schemas"]["TextDto"];
            categoryCodes?: string[];
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            actorName?: string;
        };
        MapView: {
            community?: components["schemas"]["CommunityRef"];
            lang?: string;
            cases?: components["schemas"]["CaseCard"][];
            initiatives?: components["schemas"]["MapInitiative"][];
        };
        MeView: {
            id?: components["schemas"]["UUID"];
            login?: string;
            displayName?: string;
            locale?: string;
            memberships?: components["schemas"]["MembershipView"][];
        };
        MediaView: {
            id?: components["schemas"]["UUID"];
            kind?: string;
            mimeType?: string;
            url?: string;
        };
        MembershipView: {
            community?: string;
            communityName?: string;
            role?: string;
            actorId?: components["schemas"]["UUID"];
            actorName?: string;
        };
        ModerationDetail: {
            helpers?: components["schemas"]["Helper"][];
            categoryLabel?: string;
            areaLabel?: string;
            title?: components["schemas"]["TextDto"];
            number?: string;
            createdAt?: components["schemas"]["Instant"];
            urgency?: string;
            /** Format: int32 */
            supporterCount?: number;
            outcomes?: components["schemas"]["Outcomes"];
            me?: components["schemas"]["CaseMe"];
            id?: components["schemas"]["UUID"];
            closedAt?: components["schemas"]["Instant"];
            /** Format: double */
            lat?: number;
            tasks?: components["schemas"]["TaskView"][];
            updatedAt?: components["schemas"]["Instant"];
            playbook?: components["schemas"]["PlaybookRef"];
            summary?: components["schemas"]["TextDto"];
            resolvedAt?: components["schemas"]["Instant"];
            /** Format: double */
            lng?: number;
            exactLocation?: boolean;
            kind?: string;
            categoryCode?: string;
            community?: components["schemas"]["CommunityRef"];
            statusLabel?: string;
            timeline?: components["schemas"]["TimelineItem"][];
            /** Format: int32 */
            reportCount?: number;
            status?: string;
            reports?: components["schemas"]["ReportItem"][];
            suggestion?: components["schemas"]["SuggestionView"];
        };
        MyCase: {
            /** Format: double */
            lng?: number;
            exactLocation?: boolean;
            kind?: string;
            categoryLabel?: string;
            categoryCode?: string;
            areaLabel?: string;
            title?: components["schemas"]["TextDto"];
            community?: components["schemas"]["CommunityRef"];
            statusLabel?: string;
            number?: string;
            createdAt?: components["schemas"]["Instant"];
            urgency?: string;
            /** Format: int32 */
            supporterCount?: number;
            /** Format: int32 */
            reportCount?: number;
            id?: components["schemas"]["UUID"];
            /** Format: double */
            lat?: number;
            status?: string;
            updatedAt?: components["schemas"]["Instant"];
            role?: string;
            outcome?: string;
            canAnswerOutcome?: boolean;
            joinedAt?: components["schemas"]["Instant"];
        };
        MyPlace: {
            roles?: string[];
            actors?: components["schemas"]["ActorRef"][];
        };
        NewReportBody: {
            community?: string;
            kind?: components["schemas"]["ReportKind"];
            text?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            address?: string;
            anonymous?: boolean;
        };
        NoteBody: {
            note?: string;
        };
        /** @enum {string} */
        Outcome: "HELPED" | "NOT_HELPED" | "UNCONFIRMED";
        OutcomeBody: {
            outcome?: components["schemas"]["Outcome"];
        };
        Outcomes: {
            /** Format: int64 */
            helped?: number;
            /** Format: int64 */
            notHelped?: number;
            /** Format: int64 */
            waiting?: number;
        };
        PlaybookItem: {
            id?: components["schemas"]["UUID"];
            slug?: string;
            title?: components["schemas"]["TextDto"];
            problem?: components["schemas"]["TextDto"];
            categoryCodes?: string[];
            status?: string;
            origin?: components["schemas"]["CommunityRef"];
            /** Format: int32 */
            currentVersion?: number;
            /** Format: int32 */
            draftVersion?: number;
            /** Format: int64 */
            cases?: number;
            /** Format: double */
            similarity?: number;
        };
        PlaybookMe: {
            canPublish?: boolean;
        };
        PlaybookPick: {
            id?: components["schemas"]["UUID"];
            slug?: string;
            versionId?: components["schemas"]["UUID"];
            /** Format: int32 */
            version?: number;
            title?: components["schemas"]["TextDto"];
            origin?: string;
            problem?: components["schemas"]["TextDto"];
            steps?: components["schemas"]["StepView"][];
            effort?: components["schemas"]["EffortView"];
            /** Format: double */
            similarity?: number;
        };
        PlaybookRef: {
            id?: components["schemas"]["UUID"];
            slug?: string;
            versionId?: components["schemas"]["UUID"];
            /** Format: int32 */
            version?: number;
            title?: components["schemas"]["TextDto"];
            origin?: string;
        };
        PlaybookView: {
            id?: components["schemas"]["UUID"];
            slug?: string;
            title?: components["schemas"]["TextDto"];
            problem?: components["schemas"]["TextDto"];
            categoryCodes?: string[];
            status?: string;
            shared?: boolean;
            origin?: components["schemas"]["CommunityRef"];
            lang?: string;
            current?: components["schemas"]["VersionView"];
            draft?: components["schemas"]["VersionView"];
            versions?: components["schemas"]["VersionSummary"][];
            results?: components["schemas"]["Results"];
            me?: components["schemas"]["PlaybookMe"];
        };
        QueueItem: {
            /** Format: double */
            lng?: number;
            exactLocation?: boolean;
            kind?: string;
            categoryLabel?: string;
            categoryCode?: string;
            areaLabel?: string;
            title?: components["schemas"]["TextDto"];
            community?: components["schemas"]["CommunityRef"];
            statusLabel?: string;
            number?: string;
            createdAt?: components["schemas"]["Instant"];
            urgency?: string;
            /** Format: int32 */
            supporterCount?: number;
            /** Format: int32 */
            reportCount?: number;
            id?: components["schemas"]["UUID"];
            /** Format: double */
            lat?: number;
            status?: string;
            updatedAt?: components["schemas"]["Instant"];
            aiStatus?: string;
            suggestionId?: components["schemas"]["UUID"];
            playbookTitle?: components["schemas"]["TextDto"];
            /** Format: int32 */
            doerCount?: number;
            safetyConcern?: boolean;
        };
        QueueView: {
            community?: components["schemas"]["CommunityRef"];
            lang?: string;
            counts?: {
                [key: string]: number;
            };
            items?: components["schemas"]["QueueItem"][];
        };
        ReportItem: {
            id?: components["schemas"]["UUID"];
            author?: string;
            anonymous?: boolean;
            createdAt?: components["schemas"]["Instant"];
            kind?: string;
            inputMode?: string;
            text?: components["schemas"]["TextDto"];
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            address?: string;
            categoryCode?: string;
            urgency?: string;
            safetyConcern?: boolean;
            media?: components["schemas"]["MediaView"][];
        };
        /** @enum {string} */
        ReportKind: "NEED" | "IDEA" | "OFFER";
        ReportView: {
            id?: components["schemas"]["UUID"];
            status?: string;
            kind?: string;
            inputMode?: string;
            createdAt?: components["schemas"]["Instant"];
            text?: components["schemas"]["TextDto"];
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            address?: string;
            anonymous?: boolean;
            ai?: components["schemas"]["AiReading"];
            similarCase?: components["schemas"]["SimilarCase"];
            caseId?: components["schemas"]["UUID"];
            media?: components["schemas"]["MediaView"][];
        };
        Results: {
            /** Format: int64 */
            cases?: number;
            /** Format: int64 */
            closedCases?: number;
            /** Format: int64 */
            residentsHelped?: number;
            communities?: string[];
        };
        /** @enum {string} */
        Role: "RESIDENT" | "MODERATOR" | "DOER" | "ADMIN";
        RoleInfo: {
            role?: components["schemas"]["Role"];
            who?: {
                [key: string]: string;
            };
        };
        RoleView: {
            role?: string;
            who?: string;
        };
        Rules: {
            /** Format: int32 */
            mergeRadiusMeters?: number;
            /** Format: int32 */
            publicLocationRoundingMeters?: number;
            /** Format: int32 */
            autoCloseDays?: number;
            publicMap?: boolean;
        };
        RulesView: {
            /** Format: int32 */
            mergeRadiusMeters?: number;
            /** Format: int32 */
            publicLocationRoundingMeters?: number;
            /** Format: int32 */
            autoCloseDays?: number;
            publicMap?: boolean;
        };
        SimilarCase: {
            id?: components["schemas"]["UUID"];
            number?: string;
            title?: components["schemas"]["TextDto"];
            status?: string;
            statusLabel?: string;
            /** Format: int32 */
            reportCount?: number;
            /** Format: int32 */
            supporterCount?: number;
            /** Format: double */
            similarity?: number;
            /** Format: int32 */
            distanceMeters?: number;
        };
        SourceCase: {
            id?: components["schemas"]["UUID"];
            number?: string;
            community?: string;
        };
        StatusView: {
            status?: string;
            label?: string;
            visible?: boolean;
        };
        StepView: {
            /** Format: int32 */
            position?: number;
            title?: components["schemas"]["TextDto"];
            description?: components["schemas"]["TextDto"];
            roles?: string[];
            change?: string;
        };
        StreamEvent: {
            type?: string;
            communityId?: components["schemas"]["UUID"];
            caseId?: components["schemas"]["UUID"];
            reportId?: components["schemas"]["UUID"];
            data?: {
                [key: string]: unknown;
            };
            at?: components["schemas"]["Instant"];
        };
        SubmitReport: {
            caseId?: components["schemas"]["UUID"];
            title?: string;
            summary?: string;
            categoryCode?: string;
            urgency?: components["schemas"]["Urgency"];
        };
        SubmitResult: {
            caseId?: components["schemas"]["UUID"];
            result?: string;
        };
        SuggestionView: {
            id?: components["schemas"]["UUID"];
            status?: string;
            engine?: string;
            createdAt?: components["schemas"]["Instant"];
            reason?: components["schemas"]["TextDto"];
            playbook?: components["schemas"]["PlaybookPick"];
            doers?: components["schemas"]["CandidateView"][];
            alternatives?: components["schemas"]["Alternative"][];
        };
        TaskPatch: {
            done?: boolean;
        };
        TaskView: {
            id?: components["schemas"]["UUID"];
            /** Format: int32 */
            position?: number;
            title?: components["schemas"]["TextDto"];
            done?: boolean;
            doneAt?: components["schemas"]["Instant"];
            doneBy?: string;
            assignmentId?: components["schemas"]["UUID"];
            owner?: string;
        };
        TextDto: {
            text?: string;
            lang?: string;
            machineTranslated?: boolean;
            original?: string;
        };
        TimelineItem: {
            id?: components["schemas"]["UUID"];
            type?: string;
            at?: components["schemas"]["Instant"];
            visibility?: string;
            authorName?: string;
            actorName?: string;
            actorKind?: string;
            text?: components["schemas"]["TextDto"];
            data?: {
                [key: string]: unknown;
            };
            media?: components["schemas"]["MediaView"][];
        };
        /** Format: uuid */
        UUID: string;
        UpdateBody: {
            text?: string;
            resolve?: boolean;
        };
        /** @enum {string} */
        Urgency: "LOW" | "MEDIUM" | "HIGH" | "EMERGENCY";
        VersionSummary: {
            /** Format: int32 */
            number?: number;
            status?: string;
            draftedBy?: string;
            createdAt?: components["schemas"]["Instant"];
            publishedAt?: components["schemas"]["Instant"];
            changeNotes?: components["schemas"]["TextDto"];
        };
        VersionView: {
            id?: components["schemas"]["UUID"];
            /** Format: int32 */
            number?: number;
            status?: string;
            draftedBy?: string;
            createdAt?: components["schemas"]["Instant"];
            publishedAt?: components["schemas"]["Instant"];
            publishedBy?: string;
            changeNotes?: components["schemas"]["TextDto"];
            steps?: components["schemas"]["StepView"][];
            effort?: components["schemas"]["EffortView"];
            sourceCases?: components["schemas"]["SourceCase"][];
        };
        WorkflowState: {
            status?: components["schemas"]["CaseStatus"];
            labels?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
