package app.needs.model;

public enum CaseEventType {
    REPORT_ADDED, STATUS_CHANGED, MATCH_SUGGESTED, MATCH_APPROVED, ASSIGNMENT_ACCEPTED, ASSIGNMENT_DECLINED, HELP_OFFERED,
    UPDATE_POSTED, OUTCOME_RECORDED, PLAYBOOK_DRAFTED
}
